package com.arrudeia.feature.arrudeia.presentation.ui
import android.content.Context

enum class SubCategoryOptions(val resourceName: String) {
    SUBCATEGORY_RESTAURANT("SUBCATEGORY_RESTAURANT"),
    SUBCATEGORY_BAR("SUBCATEGORY_BAR"),
    SUBCATEGORY_BAKERY("SUBCATEGORY_BAKERY"),
    SUBCATEGORY_DESSERT("SUBCATEGORY_DESSERT"),
    SUBCATEGORY_COFFEE_SHOP("SUBCATEGORY_COFFEE_SHOP"),
    SUBCATEGORY_FAST_FOOD("SUBCATEGORY_FAST_FOOD"),
    SUBCATEGORY_FOOD_COURT("SUBCATEGORY_FOOD_COURT"),
    SUBCATEGORY_WINERY("SUBCATEGORY_WINERY"),
    SUBCATEGORY_ICE_CREAM("SUBCATEGORY_ICE_CREAM"),
    SUBCATEGORY_HOTEL("SUBCATEGORY_HOTEL"),
    SUBCATEGORY_HOSTEL("SUBCATEGORY_HOSTEL"),
    SUBCATEGORY_CAMPGROUND("SUBCATEGORY_CAMPGROUND"),
    SUBCATEGORY_COTTAGE("SUBCATEGORY_COTTAGE"),
    SUBCATEGORY_BED_AND_BREAKFAST("SUBCATEGORY_BED_AND_BREAKFAST"),
    SUBCATEGORY_PARK("SUBCATEGORY_PARK"),
    SUBCATEGORY_PLAYGROUND("SUBCATEGORY_PLAYGROUND"),
    SUBCATEGORY_BEACH("SUBCATEGORY_BEACH"),
    SUBCATEGORY_SPORT_COURT("SUBCATEGORY_SPORT_COURT"),
    SUBCATEGORY_GOLF_COURSE("SUBCATEGORY_GOLF_COURSE"),
    SUBCATEGORY_PLAZA("SUBCATEGORY_PLAZA"),
    SUBCATEGORY_PROMENADE("SUBCATEGORY_PROMENADE"),
    SUBCATEGORY_POOL("SUBCATEGORY_POOL"),
    SUBCATEGORY_SCENIC_OVERLOOK("SUBCATEGORY_SCENIC_OVERLOOK"),
    SUBCATEGORY_SKI_AREA("SUBCATEGORY_SKI_AREA"),
    SUBCATEGORY_ART_GALLERY("SUBCATEGORY_ART_GALLERY"),
    SUBCATEGORY_CASINO("SUBCATEGORY_CASINO"),
    SUBCATEGORY_CLUB("SUBCATEGORY_CLUB"),
    SUBCATEGORY_TOURIST_ATTRACTION("SUBCATEGORY_TOURIST_ATTRACTION"),
    SUBCATEGORY_MOVIE_THEATER("SUBCATEGORY_MOVIE_THEATER"),
    SUBCATEGORY_MUSEUM("SUBCATEGORY_MUSEUM"),
    SUBCATEGORY_MUSIC_VENUE("SUBCATEGORY_MUSIC_VENUE"),
    SUBCATEGORY_PERFORMANCE_ARTS_VENUE("SUBCATEGORY_PERFORMANCE_ARTS_VENUE"),
    SUBCATEGORY_GAME_CLUB("SUBCATEGORY_GAME_CLUB"),
    SUBCATEGORY_STADIUM("SUBCATEGORY_STADIUM"),
    SUBCATEGORY_THEME_PARK("SUBCATEGORY_THEME_PARK"),
    SUBCATEGORY_ZOO_AQUARIUM("SUBCATEGORY_ZOO_AQUARIUM"),
    SUBCATEGORY_RACE_TRACK("SUBCATEGORY_RACE_TRACK"),
    SUBCATEGORY_THEATER("SUBCATEGORY_THEATER"),
    SUBCATEGORY_ARTS_CRAFTS("SUBCATEGORY_ARTS_CRAFTS"),
    SUBCATEGORY_BANK_FINANCIAL("SUBCATEGORY_BANK_FINANCIAL"),
    SUBCATEGORY_SPORTING_GOODS("SUBCATEGORY_SPORTING_GOODS"),
    SUBCATEGORY_BOOKSTORE("SUBCATEGORY_BOOKSTORE"),
    SUBCATEGORY_PHOTOGRAPHY("SUBCATEGORY_PHOTOGRAPHY"),
    SUBCATEGORY_CAR_DEALERSHIP("SUBCATEGORY_CAR_DEALERSHIP"),
    SUBCATEGORY_CLOTHING_FASHION("SUBCATEGORY_CLOTHING_FASHION"),
    SUBCATEGORY_CONVENIENCE_STORE("SUBCATEGORY_CONVENIENCE_STORE"),
    SUBCATEGORY_PERSONAL_CARE("SUBCATEGORY_PERSONAL_CARE"),
    SUBCATEGORY_DEPARTMENT_STORE("SUBCATEGORY_DEPARTMENT_STORE"),
    SUBCATEGORY_PHARMACY("SUBCATEGORY_PHARMACY"),
    SUBCATEGORY_ELECTRONICS("SUBCATEGORY_ELECTRONICS"),
    SUBCATEGORY_FLORIST("SUBCATEGORY_FLORIST"),
    SUBCATEGORY_HOME_FURNISHING("SUBCATEGORY_HOME_FURNISHING"),
    SUBCATEGORY_GIFT_SHOP("SUBCATEGORY_GIFT_SHOP"),
    SUBCATEGORY_GYM_FITNESS("SUBCATEGORY_GYM_FITNESS"),
    SUBCATEGORY_SWIMMING_POOL("SUBCATEGORY_SWIMMING_POOL"),
    SUBCATEGORY_HARDWARE_STORE("SUBCATEGORY_HARDWARE_STORE"),
    SUBCATEGORY_MARKET("SUBCATEGORY_MARKET"),
    SUBCATEGORY_SUPERMARKET_GROCERY("SUBCATEGORY_SUPERMARKET_GROCERY"),
    SUBCATEGORY_JEWELRY("SUBCATEGORY_JEWELRY"),
    SUBCATEGORY_LAUNDROMAT_DRY_CLEANER("SUBCATEGORY_LAUNDROMAT_DRY_CLEANER"),
    SUBCATEGORY_SHOPPING_CENTER("SUBCATEGORY_SHOPPING_CENTER"),
    SUBCATEGORY_MUSIC_STORE("SUBCATEGORY_MUSIC_STORE"),
    SUBCATEGORY_PET_STORE_VETERINARIAN("SUBCATEGORY_PET_STORE_VETERINARIAN"),
    SUBCATEGORY_TOY_STORE("SUBCATEGORY_TOY_STORE"),
    SUBCATEGORY_TRAVEL_AGENCY("SUBCATEGORY_TRAVEL_AGENCY"),
    SUBCATEGORY_ATM("SUBCATEGORY_ATM"),
    SUBCATEGORY_CURRENCY_EXCHANGE("SUBCATEGORY_CURRENCY_EXCHANGE"),
    SUBCATEGORY_CAR_RENTAL("SUBCATEGORY_CAR_RENTAL"),
    SUBCATEGORY_CELL_PHONES("SUBCATEGORY_CELL_PHONES"),
    SUBCATEGORY_COLLEGE_UNIVERSITY("SUBCATEGORY_COLLEGE_UNIVERSITY"),
    SUBCATEGORY_SCHOOL("SUBCATEGORY_SCHOOL"),
    SUBCATEGORY_CONVENTIONS_EVENT_CENTER("SUBCATEGORY_CONVENTIONS_EVENT_CENTER"),
    SUBCATEGORY_GOVERNMENT("SUBCATEGORY_GOVERNMENT"),
    SUBCATEGORY_LIBRARY("SUBCATEGORY_LIBRARY"),
    SUBCATEGORY_CITY_HALL("SUBCATEGORY_CITY_HALL"),
    SUBCATEGORY_ORGANIZATION_ASSOCIATION("SUBCATEGORY_ORGANIZATION_ASSOCIATION"),
    SUBCATEGORY_JAIL_PRISON("SUBCATEGORY_JAIL_PRISON"),
    SUBCATEGORY_COURTHOUSE("SUBCATEGORY_COURTHOUSE"),
    SUBCATEGORY_CEMETERY("SUBCATEGORY_CEMETERY"),
    SUBCATEGORY_FIRE_DEPARTMENT("SUBCATEGORY_FIRE_DEPARTMENT"),
    SUBCATEGORY_POLICE_STATION("SUBCATEGORY_POLICE_STATION"),
    SUBCATEGORY_MILITARY("SUBCATEGORY_MILITARY"),
    SUBCATEGORY_HOSPITAL_URGENT_CARE("SUBCATEGORY_HOSPITAL_URGENT_CARE"),
    SUBCATEGORY_DOCTOR_CLINIC("SUBCATEGORY_DOCTOR_CLINIC"),
    SUBCATEGORY_OFFICES("SUBCATEGORY_OFFICES"),
    SUBCATEGORY_POST_OFFICE("SUBCATEGORY_POST_OFFICE"),
    SUBCATEGORY_RELIGIOUS_CENTER("SUBCATEGORY_RELIGIOUS_CENTER"),
    SUBCATEGORY_PRESCHOOL_DAYCARE("SUBCATEGORY_PRESCHOOL_DAYCARE"),
    SUBCATEGORY_FACTORY_INDUSTRIAL("SUBCATEGORY_FACTORY_INDUSTRIAL"),
    SUBCATEGORY_EMBASSY_CONSULATE("SUBCATEGORY_EMBASSY_CONSULATE"),
    SUBCATEGORY_INFORMATION_POINT("SUBCATEGORY_INFORMATION_POINT"),
    SUBCATEGORY_EMERGENCY_SHELTER("SUBCATEGORY_EMERGENCY_SHELTER"),
    SUBCATEGORY_LANDFILL_RECYCLING_FACILITY("SUBCATEGORY_LANDFILL_RECYCLING_FACILITY"),
    SUBCATEGORY_AIRPORT("SUBCATEGORY_AIRPORT"),
    SUBCATEGORY_BUS_STATION("SUBCATEGORY_BUS_STATION"),
    SUBCATEGORY_FERRY_PIER("SUBCATEGORY_FERRY_PIER"),
    SUBCATEGORY_SEAPORT_MARINA_HARBOR("SUBCATEGORY_SEAPORT_MARINA_HARBOR"),
    SUBCATEGORY_SUBWAY_STATION("SUBCATEGORY_SUBWAY_STATION"),
    SUBCATEGORY_TRAIN_STATION("SUBCATEGORY_TRAIN_STATION"),
    SUBCATEGORY_BRIDGE("SUBCATEGORY_BRIDGE"),
    SUBCATEGORY_TUNNEL("SUBCATEGORY_TUNNEL"),
    SUBCATEGORY_TAXI_STATION("SUBCATEGORY_TAXI_STATION"),
    SUBCATEGORY_JUNCTION_INTERCHANGE("SUBCATEGORY_JUNCTION_INTERCHANGE"),
    SUBCATEGORY_REST_AREA("SUBCATEGORY_REST_AREA"),
    SUBCATEGORY_CARPOOL_PICKUP_DROP_OFF("SUBCATEGORY_CARPOOL_PICKUP_DROP_OFF"),
    SUBCATEGORY_GAS_STATION("SUBCATEGORY_GAS_STATION"),
    SUBCATEGORY_ELETRIC_POWER_STATION("SUBCATEGORY_ELETRIC_POWER_STATION"),
    SUBCATEGORY_WORKSHOP("SUBCATEGORY_WORKSHOP"),
    SUBCATEGORY_PARKING("SUBCATEGORY_PARKING"),
    SUBCATEGORY_CAR_WASH("SUBCATEGORY_CAR_WASH");



    companion object {
        fun getStringFromEnum(context: Context, enumValue: Enum<*>): String? {
            val resId = context.resources.getIdentifier(enumValue.name, "string", context.packageName)
            return if (resId != 0) {
                context.getString(resId)
            } else {
                ""
            }
        }
    }

    fun getString(context: Context): String {
        val resId = context.resources.getIdentifier(resourceName, "string", context.packageName)
        return if (resId != 0) {
            context.getString(resId)
        } else {
            ""
        }
    }
}
