package com.arrudeia.core.profile

import android.content.Context

enum class InterestsOptions(val resourceName: String) {
    INTEREST_TRAVEL("INTEREST_TRAVEL"),
    INTEREST_GASTRONOMY("INTEREST_GASTRONOMY"),
    INTEREST_SPORTS("INTEREST_SPORTS"),
    INTEREST_MOVIES("INTEREST_MOVIES"),
    INTEREST_MUSIC("INTEREST_MUSIC"),
    INTEREST_TECHNOLOGY("INTEREST_TECHNOLOGY"),
    INTEREST_PHOTOGRAPHY("INTEREST_PHOTOGRAPHY"),
    INTEREST_ART("INTEREST_ART"),
    INTEREST_BOOKS("INTEREST_BOOKS"),
    INTEREST_FASHION("INTEREST_FASHION"),
    INTEREST_DANCE("INTEREST_DANCE"),
    INTEREST_BOARD_GAMES("INTEREST_BOARD_GAMES"),
    INTEREST_TV_SERIES("INTEREST_TV_SERIES"),
    INTEREST_CYCLING("INTEREST_CYCLING"),
    INTEREST_HIKING("INTEREST_HIKING"),
    INTEREST_POETRY("INTEREST_POETRY"),
    INTEREST_FITNESS("INTEREST_FITNESS"),
    INTEREST_MEDITATION("INTEREST_MEDITATION"),
    INTEREST_YOGA("INTEREST_YOGA"),
    INTEREST_ASTROLOGY("INTEREST_ASTROLOGY"),
    INTEREST_VOLUNTEERING("INTEREST_VOLUNTEERING"),
    INTEREST_PETS("INTEREST_PETS"),
    INTEREST_FESTIVALS("INTEREST_FESTIVALS"),
    INTEREST_AUTOMOTIVE("INTEREST_AUTOMOTIVE"),
    INTEREST_COOKING("INTEREST_COOKING"),
    INTEREST_PAINTING("INTEREST_PAINTING"),
    INTEREST_HISTORY("INTEREST_HISTORY"),
    INTEREST_POLITICS("INTEREST_POLITICS"),
    INTEREST_GARDENING("INTEREST_GARDENING"),
    INTEREST_INVESTING("INTEREST_INVESTING"),
    INTEREST_EXTREME_SPORTS("INTEREST_EXTREME_SPORTS"),
    INTEREST_THEATER("INTEREST_THEATER"),
    INTEREST_CAMPING("INTEREST_CAMPING"),
    INTEREST_ECOTOURISM("INTEREST_ECOTOURISM"),
    INTEREST_COLLECTING("INTEREST_COLLECTING"),
    INTEREST_ROCK_CLIMBING("INTEREST_ROCK_CLIMBING"),
    INTEREST_FISHING("INTEREST_FISHING"),
    INTEREST_ASTRONOMY("INTEREST_ASTRONOMY"),
    INTEREST_MARTIAL_ARTS("INTEREST_MARTIAL_ARTS"),
    INTEREST_PHILOSOPHY("INTEREST_PHILOSOPHY"),
    INTEREST_RELIGION("INTEREST_RELIGION"),
    INTEREST_GEEK_CULTURE("INTEREST_GEEK_CULTURE"),
    INTEREST_CLASSIC_CARS("INTEREST_CLASSIC_CARS"),
    INTEREST_WINE_AND_CRAFT_BEER("INTEREST_WINE_AND_CRAFT_BEER"),
    INTEREST_NATURE("INTEREST_NATURE"),
    INTEREST_STAND_UP_COMEDY("INTEREST_STAND_UP_COMEDY"),
    INTEREST_POP_CULTURE("INTEREST_POP_CULTURE"),
    INTEREST_SMART_HOME("INTEREST_SMART_HOME"),
    INTEREST_RUNNING("INTEREST_RUNNING"),
    INTEREST_WATER_SPORTS("INTEREST_WATER_SPORTS"),
    INTEREST_ROCK_MUSIC("INTEREST_ROCK_MUSIC"),
    INTEREST_POP_MUSIC("INTEREST_POP_MUSIC"),
    INTEREST_JAZZ("INTEREST_JAZZ"),
    INTEREST_BLUES("INTEREST_BLUES"),
    INTEREST_HIP_HOP("INTEREST_HIP_HOP"),
    INTEREST_CLASSICAL_MUSIC("INTEREST_CLASSICAL_MUSIC"),
    INTEREST_EDM("INTEREST_EDM"),
    INTEREST_REGGAE("INTEREST_REGGAE"),
    INTEREST_SAMBA("INTEREST_SAMBA"),
    INTEREST_MPB("INTEREST_MPB");


    companion object {
        fun getStringFromEnum(context: Context, enumValue: Enum<*>): String? {
            val resId =
                context.resources.getIdentifier(enumValue.name, "string", context.packageName)
            return if (resId != 0) {
                context.getString(resId)
            } else {
                ""
            }
        }

        fun getEnumFromString(context: Context, value: String): InterestsOptions? {
            return values().find { it.getString(context) == value }
        }

        fun getAllResourceNames(context: Context): List<String> {
            return entries.map { it.getString(context) }
        }

    }

    fun getString(context: Context): String {
        val resId = context.resources.getIdentifier(resourceName, "string", context.packageName)
        return if (resId != 0) {
            context.getString(resId)
        } else {
            ""
        }
    }

}
